# Generated by Django 3.1.7 on 2021-08-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('NAID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('content', models.TextField()),
                ('quesNum', models.IntegerField()),
                ('participantsNum', models.IntegerField()),
                ('limitNum', models.IntegerField()),
                ('CHID', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('NQID', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Complition',
            fields=[
                ('content', models.TextField()),
                ('quesNum', models.IntegerField()),
                ('participantsNum', models.IntegerField()),
                ('limitNum', models.IntegerField()),
                ('CMPID', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('NQID', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('OID', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('NOID', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('selectedNum', models.IntegerField(default=0)),
                ('score', models.IntegerField()),
                ('limitNum', models.ImageField(upload_to='')),
                ('isCorrect', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0)),
                ('publishTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('answerTime', models.DateTimeField()),
                ('isClose', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
                ('recoverNum', models.IntegerField(default=0)),
                ('limitNum', models.IntegerField()),
                ('FQID', models.CharField(max_length=64)),
            ],
        ),
    ]
