# Generated by Django 3.1.7 on 2021-08-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0004_auto_20210821_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='FQID',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='isClose',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='isDeleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
