# Generated by Django 3.1.7 on 2021-08-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0005_auto_20210821_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='recoverNum',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
